import 'package:housingapp/models/property.dart';

class MockPropertyService {
  static List<Property> getMockProperties() {
    return [
      Property(
        id: 'p1',
        type: 'permanent',
        title: 'Spacious Family Home',
        description: 'Beautiful 4-bedroom house with a large garden in a quiet neighborhood.',
        imageUrl: 'https://images.unsplash.com/photo-1580582932707-5205c56106fd?fit=crop&w=1400&q=80',
        location: 'Kampala, Central',
        price: 850000000, // UGX
        latitude: 0.3477,
        longitude: 32.5825,
        bedrooms: 4,
        bathrooms: 3,
        areaSqFt: 3200,
        houseType: 'bungalow',
        fenced: true,
      ),
      Property(
        id: 'p2',
        type: 'rental',
        title: 'Modern 2-Bedroom Apartment',
        description: 'Stylish apartment in the city center, perfect for young professionals.',
        imageUrl: 'https://images.unsplash.com/photo-1600585152915-d2a804a29b4e?fit=crop&w=1400&q=80',
        location: 'Nansana, Central',
        price: 1500000, // UGX per month
        latitude: 0.3508,
        longitude: 32.5298,
        bedrooms: 2,
        bathrooms: 2,
        areaSqFt: 1100,
        roomType: '2-bedroom',
        selfContained: true,
        fenced: false,
      ),
      Property(
        id: 'p3',
        type: 'airbnb',
        title: 'Cozy Studio with City View',
        description: 'Perfect for a short stay, close to attractions with stunning views.',
        imageUrl: 'https://images.unsplash.com/photo-1540518617-e83783a31c1f?fit=crop&w=1400&q=80',
        location: 'Kololo, Kampala',
        price: 150000, // UGX per night
        latitude: 0.3297,
        longitude: 32.5937,
        bedrooms: 1,
        bathrooms: 1,
        areaSqFt: 500,
        availableDates: [
          DateTime(2025, 7, 10), DateTime(2025, 7, 11), DateTime(2025, 7, 12),
          DateTime(2025, 7, 18), DateTime(2025, 7, 19), DateTime(2025, 7, 20),
        ],
        amenities: {'wifi': true, 'kitchen': true, 'ac': true},
        maxGuests: 2,
      ),
      Property(
        id: 'p4',
        type: 'permanent',
        title: 'Suburban Villa',
        description: 'Expansive property with multiple living areas, ideal for a large family.',
        imageUrl: 'https://images.unsplash.com/photo-1582268712399-53e7d56637e1?fit=crop&w=1400&q=80',
        location: 'Entebbe, Central',
        price: 1200000000,
        latitude: 0.0527,
        longitude: 32.4632,
        bedrooms: 5,
        bathrooms: 4,
        areaSqFt: 4500,
        houseType: 'villa',
        fenced: true,
      ),
      Property(
        id: 'p5',
        type: 'rental',
        title: 'Single Room in Shared House',
        description: 'Affordable single room with shared facilities, close to public transport.',
        imageUrl: 'https://images.unsplash.com/photo-1487679805988-a40d5885287f?fit=crop&w=1400&q=80',
        location: 'Bwaise, Kampala',
        price: 350000,
        latitude: 0.3643,
        longitude: 32.5591,
        bedrooms: 1,
        bathrooms: 1, // shared
        areaSqFt: 150,
        roomType: 'single room',
        selfContained: false,
        fenced: false,
      ),
      Property(
        id: 'p6',
        type: 'airbnb',
        title: 'Luxurious Penthouse',
        description: 'High-end penthouse with panoramic city views and exclusive amenities.',
        imageUrl: 'https://images.unsplash.com/photo-1600585152915-d2a804a29b4e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8cGVudGhvdXNlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=1400&q=80',
        location: 'Naguru, Kampala',
        price: 500000,
        latitude: 0.3392,
        longitude: 32.6186,
        bedrooms: 3,
        bathrooms: 3,
        areaSqFt: 2000,
        availableDates: [
          DateTime(2025, 7, 25), DateTime(2025, 7, 26), DateTime(2025, 7, 27),
          DateTime(2025, 8, 1), DateTime(2025, 8, 2),
        ],
        amenities: {'wifi': true, 'kitchen': true, 'pool': true, 'gym': true},
        maxGuests: 6,
      ),
       Property(
        id: 'p7',
        type: 'rental',
        title: 'Executive 3-Bedroom House',
        description: 'Spacious and private house in a gated community, ideal for families.',
        imageUrl: 'https://images.unsplash.com/photo-1560518883-ff5c42aaeaa2?fit=crop&w=1400&q=80',
        location: 'Lubowa, Central',
        price: 3000000,
        latitude: 0.2223,
        longitude: 32.5694,
        bedrooms: 3,
        bathrooms: 3,
        areaSqFt: 2000,
        roomType: '3-bedroom',
        selfContained: true,
        fenced: true,
      ),
      Property(
        id: 'p8',
        type: 'permanent',
        title: 'Prime Plot with Structure',
        description: 'Large plot of land with an old structure, perfect for redevelopment.',
        imageUrl: 'https://images.unsplash.com/photo-1579548177570-5b5c7f8f9f0f?fit=crop&w=1400&q=80', // Placeholder
        location: 'Bweyogerere, Central',
        price: 400000000,
        latitude: 0.3417,
        longitude: 32.6687,
        bedrooms: 0, // Land/structure
        bathrooms: 0,
        areaSqFt: 8000,
        houseType: 'land',
      ),
       Property(
        id: 'p9',
        type: 'airbnb',
        title: 'Budget Room near Airport',
        description: 'Simple and clean room, good for layovers or short budget stays.',
        imageUrl: 'https://images.unsplash.com/photo-1563291079-ae8385a535b9?fit=crop&w=1400&q=80',
        location: 'Entebbe, Central',
        price: 80000,
        latitude: 0.0463,
        longitude: 32.4439,
        bedrooms: 1,
        bathrooms: 1,
        areaSqFt: 250,
        availableDates: [
          DateTime(2025, 7, 15), DateTime(2025, 7, 16), DateTime(2025, 7, 17),
        ],
        amenities: {'wifi': true},
        maxGuests: 1,
      ),
       Property(
        id: 'p10',
        type: 'rental',
        title: 'Self-Contained Studio',
        description: 'Compact and efficient studio apartment in a lively area.',
        imageUrl: 'https://images.unsplash.com/photo-1542315024-e1b12b2e8f17?fit=crop&w=1400&q=80',
        location: 'Kira, Central',
        price: 700000,
        latitude: 0.3883,
        longitude: 32.6517,
        bedrooms: 1,
        bathrooms: 1,
        areaSqFt: 400,
        roomType: 'studio',
        selfContained: true,
        fenced: false,
      ),
    ];
  }
}