// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8RptpwcrFyJ4s2X9yTdNEIKcPztB5NMo',
    appId: '1:589965549051:web:8036bfb2b7216833b27f5e',
    messagingSenderId: '589965549051',
    projectId: 'housing-app-5a129',
    authDomain: 'housing-app-5a129.firebaseapp.com',
    storageBucket: 'housing-app-5a129.firebasestorage.app',
    measurementId: 'G-CW7LM51EGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzLyWJQGtXgbLzYTZPak91KLHaEy-PjCo',
    appId: '1:589965549051:android:049c803084b2bf61b27f5e',
    messagingSenderId: '589965549051',
    projectId: 'housing-app-5a129',
    storageBucket: 'housing-app-5a129.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw5xDv67_wHG4aC7O4eav191a-MbbmHYw',
    appId: '1:589965549051:ios:cba1fbeb04b89f07b27f5e',
    messagingSenderId: '589965549051',
    projectId: 'housing-app-5a129',
    storageBucket: 'housing-app-5a129.firebasestorage.app',
    iosBundleId: 'com.example.housingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw5xDv67_wHG4aC7O4eav191a-MbbmHYw',
    appId: '1:589965549051:ios:cba1fbeb04b89f07b27f5e',
    messagingSenderId: '589965549051',
    projectId: 'housing-app-5a129',
    storageBucket: 'housing-app-5a129.firebasestorage.app',
    iosBundleId: 'com.example.housingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8RptpwcrFyJ4s2X9yTdNEIKcPztB5NMo',
    appId: '1:589965549051:web:204c8a60031aaffab27f5e',
    messagingSenderId: '589965549051',
    projectId: 'housing-app-5a129',
    authDomain: 'housing-app-5a129.firebaseapp.com',
    storageBucket: 'housing-app-5a129.firebasestorage.app',
    measurementId: 'G-8KF546ZT6M',
  );
}
